apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: 924338258393.dkr.ecr.us-east-1.amazonaws.com/ayodejiimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myproject
    k8s-app: myproject
  name: myproject
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: myproject
